### ISSUE TITLE
Arrow navigation keys collide when scrolling with them.

### ISSUE THREAD

**Issue by ohuang12** [DNAinator/dnainator#120]
Using the left arrow key to scroll in the strain view causes the view to lose focus due to the open pane on the left.

**Comment by Unia** [comment]
I don't really get what you mean by the title. Could you elaborate?

**Comment by pvanagtmaal** [comment]
When scrolling with the left arrow key, the event gets consumed by some other entity than the strain view., resulting in a non-persistent key press.

**Comment by Unia** [comment]
Yes, I got that from the body of the issue. The title however, mentions colliding keys. I don't get that.

**Comment by ohuang12** [comment]
The arrow keys are regarded as "navigation keys", so whenever you press an arrow key, the key event will be used for both navigation and our own defined actions. Thus navigation collides with our own defined actions.

**Comment by Unia** [comment]
Oh, I see. That clears things up :)
