### ISSUE TITLE
Graphing library

### ISSUE THREAD

**Issue by gfokkema** [DNAinator/dnainator#30]
Advantages of GraphStream:
- provides real time graphing layouts

Disadvantages of GraphStream
- layouts do not scale well since layouts try to compute and display the whole graph
- included layouts are not sufficient, HierarchicalLayout is broken
- layout interface is quite ugly and weird
- all force algorithms are O(n log(n))
- in short: GraphStream seems to be built with Force algorithms in mind,
  all nodes respond to forces of other nodes

Advantages of Gephi
- DAGLayout is exactly what we want
- professional API that looks a lot cleaner than graphstream

Disadvantages of Gephi
- layout is not really interactive
- graph disappears when panning etc.
- seems to be built with graph rendering in mind, thus create a graph once,
  then render it for multiple minutes

Advantages of drawing ourselves:
- possibly JavaFX
- dynamically loading is a lot easier, by using streams
- the way another team did it, all drawing can be done with O(n) algorithm,
  since only direct neighbors are drawn everytime
- we can still use GraphStream as our backend (or any other general purpose graph library).
- since dynamic loading is easier, integration with for example neo4j is also easier

Disadvantages of drawing ourselves:
- more work?
- GUI has to be redone

**Comment by pvanagtmaal** [comment]
I would go for the latter, as at enables us to decide what we really want and what not. This however, will require excellent planning and layout of the final product as we see it, as it is indeed more work and requires us to make up for a week of (partial) useless work, except for the parser.

**Comment by Balletie** [comment]
Visualization is obviously the part where we need full control, so drawing ourselves is a good option.
