### ISSUE TITLE
Singleton ja / nee?

### ISSUE THREAD

**Issue by gfokkema** [DNAinator/dnainator#42]
In verband met uitblijvende meningen / reacties:

singleton ja / nee?
ja:
-- je kunt er makkelijk bij
-- je hoeft vanuit de UI de neo4j db niet door te geven
nee:
-- je kunt meerdere keren nieuwe strains inladen zonder je applicatie af te sluiten
-- een singleton is een singleton, dus je mag nooit zero instances hebben (dus niet herstarten)

als je geen singleton doet, dan moet je probably het volgende hebben:

- een javafx databasecreationservice die exceptions catcht en aan de UI laat zien
-— database creation service returnt database service voor graphmodel 
- een javafx fileloadingservice die de files aan _een_ willekeurige db kan geven (db voor het laden setten in de service)
-— fileloading service moet de db op kunnen vragen aan het gebruikte model?

**Comment by Unia** [comment]
For reference, the implemented solution was to have a singleton that manages database instances.
