### ISSUE TITLE
OpenDialog should allow only one instance

### ISSUE THREAD

**Issue by pvanagtmaal** [DNAinator/dnainator#79]
the following: 
    ctrl+o
    click node box
    alt-tab alt-tab
    click node box, select node file
    click nwk box, select nwk file
    click cancel
    select node file
causes cancel to load a file. 
Furthermore, many, many, many instances can be created of the OpenDialog, leading to something like the image below
![screen shot 2015-05-22 at 23 00 47](https://cloud.githubusercontent.com/assets/5946464/7779678/d3a90416-00d6-11e5-8b13-74eca403f815.png)

**Comment by gfokkema** [comment]
Also, loading is possible by clicking on the cancel button.

dus, bear with me:
ctrl+o
klik node box
alt-tab alt-tab
klik node box, vul node file in
klik nwk box, vul nwk file in
klik cancel
vul node file in

**Comment by pvanagtmaal** [comment]
OpenDialog does not exist anymore.
